### ISSUE TITLE
Found some errors

### ISSUE THREAD

**Issue by sabershahhoseini** [sinabehmanesh/RTM#1]
Good job mate, i'm gonna use this task manager.
Found some errors:
1- `logfile not found` error. That's because you dump logs into a `log` folder but you do not initially create it in your script.
2- The `--table-columns` did not work for me and I got error. I changed it to `-columns` instead and it worked.

Also it would be good to delete the tasks by number assigned to them.
Good job ma man! keep it up!

**Comment by sinabehmanesh** [comment]
hello saber,
thank you for your feedback.

1- the logfile is a directory that is inside the .gitignore, we should probably add a statement to check if  the log directory exists and if not then it creates it. maybe we can have your PR on this? 

2- column is the same at almost every unix system, but in this case i will find a better way for the matter of sort and grid information. if you had any options in mind please let me know.

kind regards mate :)

**Comment by sinabehmanesh** [comment]
Updates:
logfile not found fixed and now it is able to check if directory exists and if not it creates its own.

**Comment by sabershahhoseini** [comment]
You got my PR mate. More info under PR comment.
